Repository R5C-V15T6AMD5S/Unity-GameHub, pull requests merged in 2024-04, with the labels that each got.

#32 SG Main Menu + Map - promjene i uređenje mapa
  Sketch_n_Guess/Assets/Animations/Crossfade.controller
  Sketch_n_Guess/Assets/LevelLoader.cs
  Sketch_n_Guess/Assets/MainMenuFunctions.cs
  Sketch_n_Guess/Assets/Prefabs.meta
  Sketch_n_Guess/Assets/Prefabs/LevelLoader.prefab
  Sketch_n_Guess/Assets/Prefabs/LevelLoader.prefab.meta
  Sketch_n_Guess/Assets/Scenes/Main Menu.unity
  Sketch_n_Guess/Assets/Scenes/Map.unity
  Sketch_n_Guess/Assets/Scenes/Multiplayer Room.unity
  Sketch_n_Guess/Assets/Scenes/Multiplayer Room.unity.meta
  Sketch_n_Guess/Assets/Scripts.meta
  Sketch_n_Guess/Assets/Scripts/LevelLoader.cs
  Sketch_n_Guess/Assets/Scripts/LevelLoader.cs.meta
  Sketch_n_Guess/Assets/Scripts/Main Menu.meta
  Sketch_n_Guess/Assets/Scripts/Main Menu/DrawWithMouse.cs
  Sketch_n_Guess/Assets/Scripts/Main Menu/DrawWithMouse.cs.meta
  Sketch_n_Guess/Assets/Scripts/Main Menu/OptionMenuSTG.cs
  Sketch_n_Guess/Assets/Scripts/Main Menu/OptionMenuSTG.cs.meta
  Sketch_n_Guess/Assets/Scripts/Multiplayer.meta
  Sketch_n_Guess/Assets/Scripts/Singleplayer.meta
  Sketch_n_Guess/Assets/Scripts/Singleplayer/ButtonControls.cs
  Sketch_n_Guess/Assets/Scripts/Singleplayer/ButtonControls.cs.meta
  Sketch_n_Guess/Assets/Scripts/Singleplayer/LevelButtonManager.cs
  Sketch_n_Guess/Assets/Scripts/Singleplayer/LevelButtonManager.cs.meta
  Sketch_n_Guess/Assets/Scripts/Singleplayer/Player.cs
  Sketch_n_Guess/Assets/Scripts/Singleplayer/Player.cs.meta
  Sketch_n_Guess/Assets/Scripts/Singleplayer/PlayerData.cs
  Sketch_n_Guess/Assets/Scripts/Singleplayer/PlayerData.cs.meta
  Sketch_n_Guess/Assets/Scripts/Singleplayer/SaveLoadFunctions.cs
  Sketch_n_Guess/Assets/Scripts/Singleplayer/SaveLoadFunctions.cs.meta
Labels: enhancement

#49 Komentiran sav kod za generaciju svijeta. Closes #42, closes #17
  MinecraftSim/Assets/_Scripts/BiomeGenerator.cs
  MinecraftSim/Assets/_Scripts/BlockDataManager.cs
  MinecraftSim/Assets/_Scripts/BlockDataSO.cs
  MinecraftSim/Assets/_Scripts/BlockHelper.cs
  MinecraftSim/Assets/_Scripts/BlockLayers/AirLayerHandler.cs
  MinecraftSim/Assets/_Scripts/BlockLayers/BlockLayerHandler.cs
  MinecraftSim/Assets/_Scripts/BlockLayers/StoneLayerHandler.cs
  MinecraftSim/Assets/_Scripts/BlockLayers/SurfaceLayerHandler.cs
  MinecraftSim/Assets/_Scripts/BlockLayers/UndergroundLayerHandler.cs
  MinecraftSim/Assets/_Scripts/BlockLayers/WaterLayerHandler.cs
  MinecraftSim/Assets/_Scripts/BlockType.cs
  MinecraftSim/Assets/_Scripts/Chunk.cs
  MinecraftSim/Assets/_Scripts/ChunkData.cs
  MinecraftSim/Assets/_Scripts/ChunkRenderer.cs
  MinecraftSim/Assets/_Scripts/Direction.cs
  MinecraftSim/Assets/_Scripts/DirectionExtensions.cs
  MinecraftSim/Assets/_Scripts/DomainWarping.cs
  MinecraftSim/Assets/_Scripts/MeshData.cs
  MinecraftSim/Assets/_Scripts/MyNoise.cs
  MinecraftSim/Assets/_Scripts/NoiseSettings.cs
  MinecraftSim/Assets/_Scripts/TerrainGenerator.cs
  MinecraftSim/Assets/_Scripts/World.cs
  MinecraftSim/Assets/_Scripts/WorldDataHelper.cs
Labels: documentation, enhancement

#75 SG - Multiplayer Početak
  Sketch_n_Guess/Assets/Scenes/Multiplayer Room.unity
  Sketch_n_Guess/Assets/Scripts/LevelLoader.cs
  Sketch_n_Guess/Assets/Scripts/Main Menu/DrawWithMouse.cs
  Sketch_n_Guess/Assets/Scripts/Main Menu/OptionMenuSTG.cs
  Sketch_n_Guess/Assets/Scripts/Singleplayer/LevelButtonManager.cs
  Sketch_n_Guess/Assets/Scripts/Singleplayer/Player.cs
  Sketch_n_Guess/Assets/Scripts/Singleplayer/SaveLoadFunctions.cs
Labels: duplicate, enhancement
