Repository R5C-V15T6AMD5S/Unity-GameHub, pull requests merged in 2024-05, with the labels that each got.

#90 SG: MP: Crtanje + Chat + Pogađanje
  Sketch_n_Guess/Assets/DefaultNetworkPrefabs.asset
  Sketch_n_Guess/Assets/DefaultNetworkPrefabs.asset.meta
  Sketch_n_Guess/Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Sketch_n_Guess/Assets/Prefabs/Line.prefab
  Sketch_n_Guess/Assets/Prefabs/Message.prefab
  Sketch_n_Guess/Assets/Prefabs/Message.prefab.meta
  Sketch_n_Guess/Assets/Scenes/Multiplayer Connect.unity
  Sketch_n_Guess/Assets/Scenes/Multiplayer Gameplay.unity
  Sketch_n_Guess/Assets/Scenes/Multiplayer Lobby.unity
  Sketch_n_Guess/Assets/Scripts/Multiplayer/ChatManager.cs
  Sketch_n_Guess/Assets/Scripts/Multiplayer/ChatManager.cs.meta
  Sketch_n_Guess/Assets/Scripts/Multiplayer/GuessedWordCorrectness.cs
  Sketch_n_Guess/Assets/Scripts/Multiplayer/GuessedWordCorrectness.cs.meta
  Sketch_n_Guess/Assets/Scripts/Multiplayer/LobbyManager.cs
  Sketch_n_Guess/Assets/Scripts/Multiplayer/PlayerChat.cs
  Sketch_n_Guess/Assets/Scripts/Multiplayer/UserMessages.cs
  Sketch_n_Guess/Assets/Scripts/Multiplayer/UserMessages.cs.meta
  Sketch_n_Guess/Assets/Scripts/Singleplayer/LineGenerator.cs
  Sketch_n_Guess/Packages/manifest.json
  Sketch_n_Guess/Packages/packages-lock.json
Labels: enhancement

#94 Minecraft visedretvenost i korutine
  MinecraftSim/Assets/Scenes/VoxelWorld.unity
  MinecraftSim/Assets/_Scripts/World.cs
  MinecraftSim/Assets/_Scripts/WorldDataHelper.cs
  MinecraftSim/Assets/_Scripts/WorldRenderer.cs
  MinecraftSim/Assets/_Scripts/WorldRenderer.cs.meta
Labels: enhancement

#102 Minecraft implementacija drveća
  MinecraftSim/Assets/Scenes/VoxelWorld.unity
  MinecraftSim/Assets/_Scripts/BiomeGenerator.cs
  MinecraftSim/Assets/_Scripts/Chunk.cs
  MinecraftSim/Assets/_Scripts/ChunkData.cs
  MinecraftSim/Assets/_Scripts/TerrainGenerator.cs
  MinecraftSim/Assets/_Scripts/Trees.meta
  MinecraftSim/Assets/_Scripts/Trees/DataProcessing.cs
  MinecraftSim/Assets/_Scripts/Trees/DataProcessing.cs.meta
  MinecraftSim/Assets/_Scripts/Trees/TreeData.cs
  MinecraftSim/Assets/_Scripts/Trees/TreeData.cs.meta
  MinecraftSim/Assets/_Scripts/Trees/TreeGenerator.cs
  MinecraftSim/Assets/_Scripts/Trees/TreeGenerator.cs.meta
  MinecraftSim/Assets/_Scripts/Trees/TreeLayerHandler.cs
  MinecraftSim/Assets/_Scripts/Trees/TreeLayerHandler.cs.meta
  MinecraftSim/Assets/_Scripts/World.cs
  MinecraftSim/Assets/_Scripts/WorldDataHelper.cs
  MinecraftSim/Assets/_Scripts/treeNoiseSettings.asset
  MinecraftSim/Assets/_Scripts/treeNoiseSettings.asset.meta
Labels: bug, enhancement

#104 Minecraft ažuriranje chunkova
  MinecraftSim/Assets/_Scripts/BiomeGenerator.cs
  MinecraftSim/Assets/_Scripts/Chunk.cs
  MinecraftSim/Assets/_Scripts/Player/Character.cs
  MinecraftSim/Assets/_Scripts/World.cs
  MinecraftSim/Assets/_Scripts/WorldDataHelper.cs
Labels: bug, enhancement

#108 SG - Opcija za GameHub
  GameHub/.gitignore
  GameHub/.vscode/extensions.json
  GameHub/.vscode/launch.json
  GameHub/.vscode/settings.json
  GameHub/Assets/Fonts.meta
  GameHub/Assets/Fonts/Wonder Boys - Personal Use.ttf
  GameHub/Assets/Fonts/Wonder Boys - Personal Use.ttf.meta
  GameHub/Assets/Images.meta
  GameHub/Assets/Images/sg_title_logo.png
  GameHub/Assets/Images/sg_title_logo.png.meta
  GameHub/Assets/Scenes.meta
  GameHub/Assets/Scenes/Main Screen.unity
  GameHub/Assets/Scenes/Main Screen.unity.meta
  GameHub/Assets/Scripts.meta
  GameHub/Assets/Scripts/GameLauncher.cs
  GameHub/Assets/Scripts/GameLauncher.cs.meta
  GameHub/Assets/Scripts/GameLauncherLinux.cs
  GameHub/Assets/Scripts/GameLauncherLinux.cs.meta
  GameHub/Packages/manifest.json
  GameHub/Packages/packages-lock.json
  GameHub/ProjectSettings/AudioManager.asset
  GameHub/ProjectSettings/ClusterInputManager.asset
  GameHub/ProjectSettings/DynamicsManager.asset
  GameHub/ProjectSettings/EditorBuildSettings.asset
  GameHub/ProjectSettings/EditorSettings.asset
  GameHub/ProjectSettings/GraphicsSettings.asset
  GameHub/ProjectSettings/InputManager.asset
  GameHub/ProjectSettings/MemorySettings.asset
  GameHub/ProjectSettings/NavMeshAreas.asset
  GameHub/ProjectSettings/NetworkManager.asset
  GameHub/ProjectSettings/PackageManagerSettings.asset
  GameHub/ProjectSettings/Physics2DSettings.asset
  GameHub/ProjectSettings/PresetManager.asset
  GameHub/ProjectSettings/ProjectSettings.asset
  GameHub/ProjectSettings/ProjectVersion.txt
  GameHub/ProjectSettings/QualitySettings.asset
  GameHub/ProjectSettings/SceneTemplateSettings.json
  GameHub/ProjectSettings/TagManager.asset
  GameHub/ProjectSettings/TimeManager.asset
  GameHub/ProjectSettings/UnityConnectSettings.asset
  GameHub/ProjectSettings/VFXManager.asset
  GameHub/ProjectSettings/VersionControlSettings.asset
  GameHub/ProjectSettings/XRSettings.asset
  Sketch_n_Guess/Assets/Scenes/Multiplayer Gameplay.unity
  Sketch_n_Guess/Assets/Scripts/Multiplayer/LobbyManager.cs
Labels: enhancement, help wanted

#111 SG: README + Actions workflow
  .github/workflows/updates_readme.yml
  README.md
Labels: documentation, enhancement

#114 SG: Popravak errora za workflow i bolje formulirana poruka
  .github/workflows/updates_readme.yml
Labels: documentation, duplicate, enhancement

#113 Minecraft implementacija bioma
  MinecraftSim/Assets/Scenes/VoxelWorld.unity
  MinecraftSim/Assets/_Scripts/BiomeCenterFinder.cs
  MinecraftSim/Assets/_Scripts/BiomeCenterFinder.cs.meta
  MinecraftSim/Assets/_Scripts/BiomeGenerator.cs
  MinecraftSim/Assets/_Scripts/BiomeTemperatureNoiseSettings.asset
  MinecraftSim/Assets/_Scripts/BiomeTemperatureNoiseSettings.asset.meta
  MinecraftSim/Assets/_Scripts/BlockHelper.cs
  MinecraftSim/Assets/_Scripts/TerrainGenerator.cs
  MinecraftSim/Assets/_Scripts/World.cs
Labels: bug, enhancement

#115 Minecraft
  MinecraftSim/Assets/Scenes/VoxelWorld.unity
  MinecraftSim/Assets/_Scripts/BiomeCenterFinder.cs
  MinecraftSim/Assets/_Scripts/BiomeCenterFinder.cs.meta
  MinecraftSim/Assets/_Scripts/BiomeGenerator.cs
  MinecraftSim/Assets/_Scripts/BiomeTemperatureNoiseSettings.asset
  MinecraftSim/Assets/_Scripts/BiomeTemperatureNoiseSettings.asset.meta
  MinecraftSim/Assets/_Scripts/BlockHelper.cs
  MinecraftSim/Assets/_Scripts/Chunk.cs
  MinecraftSim/Assets/_Scripts/ChunkData.cs
  MinecraftSim/Assets/_Scripts/Player/Character.cs
  MinecraftSim/Assets/_Scripts/TerrainGenerator.cs
  MinecraftSim/Assets/_Scripts/Trees.meta
  MinecraftSim/Assets/_Scripts/Trees/DataProcessing.cs
  MinecraftSim/Assets/_Scripts/Trees/DataProcessing.cs.meta
  MinecraftSim/Assets/_Scripts/Trees/TreeData.cs
  MinecraftSim/Assets/_Scripts/Trees/TreeData.cs.meta
  MinecraftSim/Assets/_Scripts/Trees/TreeGenerator.cs
  MinecraftSim/Assets/_Scripts/Trees/TreeGenerator.cs.meta
  MinecraftSim/Assets/_Scripts/Trees/TreeLayerHandler.cs
  MinecraftSim/Assets/_Scripts/Trees/TreeLayerHandler.cs.meta
  MinecraftSim/Assets/_Scripts/World.cs
  MinecraftSim/Assets/_Scripts/WorldDataHelper.cs
  MinecraftSim/Assets/_Scripts/WorldRenderer.cs
  MinecraftSim/Assets/_Scripts/WorldRenderer.cs.meta
  MinecraftSim/Assets/_Scripts/treeNoiseSettings.asset
  MinecraftSim/Assets/_Scripts/treeNoiseSettings.asset.meta
Labels: bug, enhancement

#123 Optimizacija workflow-a
  .github/workflows/updates_readme.yml
Labels: documentation, enhancement

#126 Uspostavljeni direktoriji za testiranje.
  MinecraftSim/Assets/EditTests.meta
  MinecraftSim/Assets/EditTests/EditTests.meta
  MinecraftSim/Assets/EditTests/EditTests/EditTests.asmdef
  MinecraftSim/Assets/EditTests/EditTests/EditTests.asmdef.meta
  MinecraftSim/Assets/PlayTests.meta
  MinecraftSim/Assets/PlayTests/PlayTests.meta
  MinecraftSim/Assets/PlayTests/PlayTests/PlayTests.asmdef
  MinecraftSim/Assets/PlayTests/PlayTests/PlayTests.asmdef.meta
  MinecraftSim/Assets/_Scripts/AssemblyHookTests.asmdef
  MinecraftSim/Assets/_Scripts/AssemblyHookTests.asmdef.meta
Labels: enhancement, testing

#128 Dodani testovi koji provjeravaju Chunk i WorldDataHelper.
  MinecraftSim/Assets/EditTests/EditTests/ChunkTest.cs
  MinecraftSim/Assets/EditTests/EditTests/ChunkTest.cs.meta
  MinecraftSim/Assets/EditTests/EditTests/WorldDataHelperTest.cs
  MinecraftSim/Assets/EditTests/EditTests/WorldDataHelperTest.cs.meta
  MinecraftSim/Assets/Scenes/VoxelWorld.unity
  MinecraftSim/Assets/_Scripts/AssemblyInfo.cs
  MinecraftSim/Assets/_Scripts/AssemblyInfo.cs.meta
  MinecraftSim/ProjectSettings/ProjectSettings.asset
  MinecraftSim/ProjectSettings/TagManager.asset
Labels: testing
