Repository R5C-V15T6AMD5S/Unity-GameHub, pull requests merged in 2024-06, with the labels that each got.

#130 Dodan workflow za Minecraft granu.
  .github/failure.md
  .github/workflows/minecraft-tests.yml
Labels: enhancement, testing

#132 Dodana putanja za MinecraftSim.sln
  .github/workflows/minecraft-tests.yml
Labels: bug

#134 Dodan solution datoteka, uz izmjenu u gitignore.
  MinecraftSim/.gitignore
  MinecraftSim/MinecraftSim.sln
Labels: bug

#136 Omogućeno dodavanje test projekata.
  MinecraftSim/.gitignore
  MinecraftSim/Assembly-CSharp-Editor.csproj
  MinecraftSim/Assembly-CSharp.csproj
  MinecraftSim/AssemblyHookTests.csproj
  MinecraftSim/EditTests.csproj
Labels: bug

#138 Navedena ispravna putanja EditTests.csproj.
  .github/workflows/minecraft-tests.yml
Labels: bug

#139 Dodana komanda koja popraviti spremanje rezultata testa.
  .github/workflows/minecraft-tests.yml
Labels: bug

#140 Izvršavanje testova kroz Unity.
  .github/workflows/minecraft-tests.yml
Labels: bug

#141 Pokušaj popravka pokretanja unity-ja.
  .github/workflows/minecraft-tests.yml
Labels: bug

#142 Pokušaj popravka pokretanja Unityja.
  .github/workflows/minecraft-tests.yml
Labels: bug

#147 Minecraft workflow
  .github/workflows/minecraft-tests.yml
Labels: bug

#149 Proba za rad workflowa.
  WorkflowProba.txt
Labels: bug

#151 Proba za workflow 2.
  WorkflowProba.txt
Labels: bug

#153 Dodan workflow za testiranje merge-a.
  .github/sg_failure.md
  .github/workflows/sketch-n-guess_tests.yml
Labels: enhancement, testing

#154 Test za SG workflow.
  SG_WorkflowTest.txt
Labels: enhancement, testing

#159 Provjera workflowa.
  WorkflowProba.txt
Labels: bug

#166 Ispravljanje pozicije health bar-a. Closes #164.
  MinecraftSim/ProjectSettings/ProjectSettings.asset
Labels: bug

#169 Dodane skripte za AI guess
  Sketch_n_Guess/Assets/Scripts/AI.meta
  Sketch_n_Guess/Assets/Scripts/AI/DollarPoint.cs
  Sketch_n_Guess/Assets/Scripts/AI/DollarPoint.cs.meta
  Sketch_n_Guess/Assets/Scripts/AI/RecognitionAlgorithm.cs
  Sketch_n_Guess/Assets/Scripts/AI/RecognitionAlgorithm.cs.meta
  Sketch_n_Guess/Assets/Scripts/AI/RecognitionManager.cs
  Sketch_n_Guess/Assets/Scripts/AI/RecognitionManager.cs.meta
  Sketch_n_Guess/Assets/Scripts/AI/Recognizer.cs
  Sketch_n_Guess/Assets/Scripts/AI/Recognizer.cs.meta
Labels: bug, enhancement

#170 Dodani komentari
  Sketch_n_Guess/Assets/Scripts/AI/RecognitionAlgorithm.cs
  Sketch_n_Guess/Assets/Scripts/AI/RecognitionManager.cs
  Sketch_n_Guess/Assets/Scripts/AI/Recognizer.cs
Labels: bug, enhancement
